// <auto-generated />
using System;
using Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;

#nullable disable

namespace Challenge1.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            OracleModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Domain.Entities.EnderecoEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ENDERECO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Bairro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("BAIRRO");

                    b.Property<string>("Cep")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("CEP");

                    b.Property<string>("Cidade")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("CIDADE");

                    b.Property<string>("Complemento")
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("COMPLEMENTO");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("ESTADO");

                    b.Property<string>("Logradouro")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("LOGRADOURO");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("NUMERO");

                    b.HasKey("Id");

                    b.ToTable("MOTTU_ENDERECO");
                });

            modelBuilder.Entity("Domain.Entities.FilialEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_FILIAL");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ativo")
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("ATIVO");

                    b.Property<string>("Cnpj")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("CNPJ");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<long>("IdEndereco")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ENDERECO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Telefone")
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("Id");

                    b.ToTable("MOTTU_FILIAL");
                });

            modelBuilder.Entity("Domain.Entities.HistoricoLocalizacaoEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_HISTORICO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime?>("DataHoraEntrada")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_HORA_ENTRADA");

                    b.Property<DateTime>("DataHoraSaida")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_HORA_SAIDA");

                    b.Property<long>("IdMoto")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_MOTO");

                    b.Property<long?>("IdMotociclista")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_MOTOCICLISTA");

                    b.Property<long?>("IdStatusOperacao")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_STATUS_OPERACAO");

                    b.Property<long?>("IdZonaPatio")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ZONA_PATIO");

                    b.Property<decimal?>("KmRodados")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("KM_RODADOS");

                    b.HasKey("Id");

                    b.ToTable("MOTTU_HISTORICO_LOCALIZACAO");
                });

            modelBuilder.Entity("Domain.Entities.LocalizacaoMotoEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_LOCALIZACAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<DateTime>("DataHoraEntrada")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_HORA_ENTRADA");

                    b.Property<DateTime?>("DataHoraSaida")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_HORA_SAIDA");

                    b.Property<long>("IdMoto")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_MOTO");

                    b.Property<long>("IdZona")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ZONA");

                    b.HasKey("Id");

                    b.ToTable("MOTTU_LOCALIZACAO_MOTO");
                });

            modelBuilder.Entity("Domain.Entities.MotoEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_MOTO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<int>("AnoFabricacao")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ANO_FABRICACAO");

                    b.Property<int>("AnoModelo")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("ANO_MODELO");

                    b.Property<string>("Chassi")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("NVARCHAR2(17)")
                        .HasColumnName("CHASSI");

                    b.Property<int>("Cilindrada")
                        .HasColumnType("NUMBER(10)")
                        .HasColumnName("CILINDRADA");

                    b.Property<string>("Cor")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("COR");

                    b.Property<DateTime>("DataAquisicao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_AQUISICAO");

                    b.Property<long?>("IdNotaFiscal")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_NF");

                    b.Property<long>("IdStatus")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_STATUS");

                    b.Property<long>("IdTipo")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_TIPO");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("MODELO");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("NVARCHAR2(10)")
                        .HasColumnName("PLACA");

                    b.Property<decimal>("ValorAquisicao")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("VALOR_AQUISICAO");

                    b.HasKey("Id");

                    b.ToTable("MOTTU_MOTO");
                });

            modelBuilder.Entity("Domain.Entities.MotociclistaEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_MOTOCICLISTA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Ativo")
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("ATIVO");

                    b.Property<string>("Cnh")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("CNH");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("NVARCHAR2(11)")
                        .HasColumnName("CPF");

                    b.Property<DateTime>("DataCadastro")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_CADASTRO");

                    b.Property<DateTime>("DataValidadeCnh")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_VALIDADE_CNH");

                    b.Property<string>("Email")
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("EMAIL");

                    b.Property<long?>("IdEndereco")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ENDERECO");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("NOME");

                    b.Property<string>("Telefone")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TELEFONE");

                    b.HasKey("Id");

                    b.ToTable("MOTTU_MOTOCILCISTA");
                });

            modelBuilder.Entity("Domain.Entities.NotaFiscalEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_NF");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("ChaveAcesso")
                        .HasMaxLength(44)
                        .HasColumnType("NVARCHAR2(44)")
                        .HasColumnName("CHAVE_ACESSO");

                    b.Property<string>("CnpjFornecedor")
                        .IsRequired()
                        .HasMaxLength(14)
                        .HasColumnType("NVARCHAR2(14)")
                        .HasColumnName("CNPJ_FORNECEDOR");

                    b.Property<DateTime>("DataEmissao")
                        .HasColumnType("TIMESTAMP(7)")
                        .HasColumnName("DATA_EMISSAO");

                    b.Property<string>("Fornecedor")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("NVARCHAR2(100)")
                        .HasColumnName("FORNECEDOR");

                    b.Property<string>("Modelo")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("NVARCHAR2(2)")
                        .HasColumnName("MODELO");

                    b.Property<string>("Numero")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("NUMERO");

                    b.Property<string>("Serie")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("NVARCHAR2(5)")
                        .HasColumnName("SERIE");

                    b.Property<decimal>("ValorTotal")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("VALOR_TOTAL");

                    b.HasKey("Id");

                    b.ToTable("MOTTU_NF");
                });

            modelBuilder.Entity("Domain.Entities.PatioEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PATIO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<decimal?>("AreaM2")
                        .HasColumnType("DECIMAL(18, 2)")
                        .HasColumnName("AREA_M2");

                    b.Property<string>("Ativo")
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("ATIVO");

                    b.Property<long>("Capacidade")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CAPACIDADE");

                    b.Property<long>("IdFilial")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_FILIAL");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("NOME");

                    b.HasKey("Id");

                    b.ToTable("MOTTU_PATIO");
                });

            modelBuilder.Entity("Domain.Entities.StatusMotoEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_STATUS");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("Disponivel")
                        .HasMaxLength(1)
                        .HasColumnType("NVARCHAR2(1)")
                        .HasColumnName("DISPONIVEL");

                    b.HasKey("Id");

                    b.ToTable("MOTTU_STATUS_MOTO");
                });

            modelBuilder.Entity("Domain.Entities.StatusOperacaoEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_STATUS_OPERACAO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("NVARCHAR2(50)")
                        .HasColumnName("DESCRICAO");

                    b.Property<string>("TipoMovimentacao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TIPO_MOVIMENTACAO");

                    b.HasKey("Id");

                    b.ToTable("MOTTU_STATUS_OPERACAO");
                });

            modelBuilder.Entity("Domain.Entities.TipoMotoEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_TIPO");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Categoria")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("CATEGORIA");

                    b.Property<string>("Descricao")
                        .IsRequired()
                        .HasMaxLength(60)
                        .HasColumnType("NVARCHAR2(60)")
                        .HasColumnName("DESCRICAO");

                    b.HasKey("Id");

                    b.ToTable("MOTTU_TIPO_MOTO");
                });

            modelBuilder.Entity("Domain.Entities.ZonaPatioEntity", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_ZONA");

                    OraclePropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("Id"));

                    b.Property<long>("Capacidade")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("CAPACIDADE");

                    b.Property<long>("IdPatio")
                        .HasColumnType("NUMBER(19)")
                        .HasColumnName("ID_PATIO");

                    b.Property<string>("NomeZona")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("NVARCHAR2(30)")
                        .HasColumnName("NOME_ZONA");

                    b.Property<string>("TipoZona")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("NVARCHAR2(20)")
                        .HasColumnName("TIPO_ZONA");

                    b.HasKey("Id");

                    b.ToTable("MOTTU_ZONA_PATIO");
                });
#pragma warning restore 612, 618
        }
    }
}
